### ISSUE TITLE
尝试运行XalanTemplatesImpl报错

### ISSUE THREAD

**Issue by Sicmatr1x** [javaweb-sec/javaweb-sec#3]
/javaweb-sec-source/javase/src/main/java/com/anbai/sec/classloader/XalanTemplatesImpl.java

```
Exception in thread "main" com.alibaba.fastjson.JSONException: autoType is not support. com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:609)
	at hack.dynamicLoadClass.XalanTemplatesImpl.fastjsonRCE(XalanTemplatesImpl.java:203)
	at hack.dynamicLoadClass.XalanTemplatesImpl.main(XalanTemplatesImpl.java:209)
Caused by: com.alibaba.fastjson2.JSONException: autoType is not support. com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.checkAutoType(ObjectReaderProvider.java:750)
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:657)
	at com.alibaba.fastjson2.JSONReader$Context.getObjectReaderAutoType(JSONReader.java:3312)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:115)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:599)
	... 2 more
```

**Comment by javasec** [comment]
请注意fastjson的版本，javase项目使用的是1.2.23，从fastjson 1.2.25开始就会报：autoType is not support. com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl
